# Site
title:              Pratika RCC Pipes Blog
bio:                'RCC pipe manufacturers and suppliers in Hyderabad.'
description:        "Announcements and general commentary. May or may not be related to RCC pipes"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/pratika-rcc-pipes-logo.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://pratikarccpipes.com/blog
zentry:             http://pratikarccpipes.com
baseurl:            /blog

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   rccpipes

# Social
# if you don't have any of social below, comment the line.
google:
  plus:            106491477335643128020
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:             rccpipeshyderabad+sitelisting@gmail.com
twitter:            rcc_pipes
#facebook:           username
#github-url:         username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
